#!/bin/sh

#
# Docker entrypoint
#

# Defaults
if [ -z "$UVICORN_ARG_SSL_KEYFILE" ]; then
  UVICORN_ARG_SSL_KEYFILE=""
fi
if [ -z "$UVICORN_ARG_SSL_CERTFILE" ]; then
  UVICORN_ARG_SSL_CERTFILE=""
fi
if [ -z "$UVICORN_ARG_WORKERS" ]; then
  UVICORN_ARG_WORKERS="1"
fi
if [ -z "$UVICORN_ARG_HOST" ]; then
  UVICORN_ARG_HOST="0.0.0.0"
fi
if [ -z "$UVICORN_ARG_PORT" ]; then
  UVICORN_ARG_PORT="8000"
fi
if [ -z "$UVICORN_ARG_APP" ]; then
  UVICORN_ARG_APP="main:app"
fi

UVICORN_ARGS=""
UVICORN_ARGS="${UVICORN_ARGS} --workers ${UVICORN_ARG_WORKERS}"
UVICORN_ARGS="${UVICORN_ARGS} --host ${UVICORN_ARG_HOST}"
UVICORN_ARGS="${UVICORN_ARGS} --port ${UVICORN_ARG_PORT}"
UVICORN_ARGS="${UVICORN_ARGS} --workers ${UVICORN_ARG_WORKERS}"

# https://github.com/encode/uvicorn/issues/1029#issuecomment-845282034
SSL_CIPHERS="TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256"

if [ -n "$UVICORN_ARG_SSL_KEYFILE" ]; then
  UVICORN_ARGS="${UVICORN_ARGS} --ssl-ciphers=${SSL_CIPHERS} --ssl-keyfile ${UVICORN_ARG_SSL_KEYFILE}"
fi
if [ -n "$UVICORN_ARG_SSL_CERTFILE" ]; then
  UVICORN_ARGS="${UVICORN_ARGS} --ssl-certfile ${UVICORN_ARG_SSL_CERTFILE}"
fi

CMD_TO_EXEC="uvicorn --access-log --no-server-header ${UVICORN_ARGS} ${UVICORN_ARG_APP}"

echo "$CMD_TO_EXEC"

exec $CMD_TO_EXEC